# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 03:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20160925_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='fill_a',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='circle',
            name='fill_b',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='circle',
            name='fill_g',
            field=models.IntegerField(default=17, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='circle',
            name='fill_r',
            field=models.IntegerField(default=166, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
