# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_auto_20160925_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
