# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='type',
            field=models.CharField(choices=[('CI', 'CI'), ('SQ', 'SQ'), ('PO', 'PO')], default='CI', max_length=2),
        ),
    ]
