# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_actor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='type',
            new_name='shape',
        ),
    ]
