# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 20:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0009_auto_20160926_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('y', models.IntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.AlterField(
            model_name='actor',
            name='shape',
            field=models.CharField(choices=[('CI', 'Circle'), ('SQ', 'Square'), ('PO', 'Polygon')], default='CI', max_length=2),
        ),
    ]
